#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

if [ -z "${DEV_ENV:-}" ]; then
    echo "Error: DEV_ENV environment variable must be set." >&2
    exit 1
fi

export DEV_ENV="$DEV_ENV"

dry_run=0
grep_filter=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry) dry_run=1 ;;
        *) grep_filter="$1" ;;
    esac
    echo "ARG: \"$1\""
    shift
done

log() {
    if [[ $dry_run -eq 1 ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: DEV_ENV: $DEV_ENV -- grep_filter: '$grep_filter'"

if [[ "$(uname)" == "Darwin" ]]; then
    runs_dir=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -type f -perm +111)
else
    runs_dir=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -type f -executable)
fi

for s in $runs_dir; do
    if [[ -n "$grep_filter" ]] && ! echo "$s" | grep -q "$grep_filter"; then
        log "grep filter '$grep_filter' filtered out $s"
        continue
    fi

    log "Running script: $s"
    if [[ $dry_run -eq 0 ]]; then
        "$s"
    fi
done

echo "Run script completed."
