#!/usr/bin/env bash

sudo pacman -Syu --needed base-devel git
if ! command -v yay &> /dev/null; then
    git clone https://aur.archlinux.org/yay-bin.git /tmp/yay
    (cd /tmp/yay && makepkg -si --noconfirm)
fi
