#!/usr/bin/env bash

git config --global user.email "huyn.nguyen95@gmail.com"
git config --global user.name "thenameiswiiwin"

# Lua tools
yay -S --noconfirm luarocks luajit
sudo luarocks install luacheck
