#!/usr/bin/env bash

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
    else
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    fi
}
detect_os

install_node() {
    curl -fsSL https://fnm.vercel.app/install | bash
    source ~/.bashrc
    fnm install --latest
    npm install -g pnpm bun
}

case $OS in
arch)
    yay -S --noconfirm deno
    install_node
    ;;
ubuntu | debian)
    curl -fsSL https://deno.land/x/install/install.sh | sh
    install_node
    ;;
esac

echo -e "\e[1;34m[INFO]\e[0m Node script completed."
