#!/usr/bin/env bash

detect_os() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        OS=$ID
    else
        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    fi
}
detect_os

case $OS in
arch)
    yay -S --noconfirm tmux
    ;;
ubuntu | debian)
    sudo apt install -y tmux
    ;;
esac

echo -e "\e[1;34m[INFO]\e[0m TMUX script completed."
