require "thenameiswiiwin.plugins"
require "thenameiswiiwin.options"
require "thenameiswiiwin.mappings"
require "thenameiswiiwin.commands"
require "thenameiswiiwin.colors"

require "thenameiswiiwin.autocmds"
require "thenameiswiiwin.folds"
require "thenameiswiiwin.filetree"
require "thenameiswiiwin.statusline"
require "thenameiswiiwin.treesitter"
require "thenameiswiiwin.formatting"
