#!/usr/bin/env bash

if [[ "$uname" == "Linux" ]]; then
    pushd ~/personal/dev/env/.config/nvim || exit
    git add .
    git commit -m 'automated dev commit'
    git push
    popd

    pushd ~/personal/dev || exit
    git add .
    git commit -m 'automated dev commit'
    git push
    popd
else [[ "$OS" == "Darwin" ]]; then
    pushd ~/personal/dev || exit
    git add .
    git commit -m 'automated dev commit'
    git push
    popd
fi
