#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
    echo "Installing Ghostty via Homebrew..."
    brew install --cask ghostty
else
    echo "Installing Ghostty..."
    sudo apt update
    sudo apt install -y llvm lld llvm-dev liblld-dev clang libclang-dev libglib2.0-dev libgtk-4-dev libadwaita-1-dev git wget

    wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -O /tmp/zig.tar.xz
    mkdir -p "$HOME/.local"
    tar -xvf /tmp/zig.tar.xz -C "$HOME/.local"
    export PATH="$HOME/.local/zig-linux-x86_64-0.13.0:$PATH"

    git clone git@github.com:ghostty-org/ghostty.git "$HOME/personal/ghostty"
    pushd "$HOME/personal/ghostty" >/dev/null || exit 1
    zig build -p "$HOME/.local" -Doptimize=ReleaseFast
    popd >/dev/null
fi
