#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
    echo "macOS detected. Checking for Homebrew..."

    if ! command -v brew &>/dev/null; then
        echo "Homebrew not found. Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" echo 'eval "$(/usr/local/bin/brew shellenv)"' >>$HOME/.zsh_profile
        eval "$(/usr/local/bin/brew shellenv)"

        echo "Homebrew installation complete!"
    else
        echo "Homebrew is already installed."
    fi
else
    echo "Not on macOS. Skipping Homebrew installation."
fi
