#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
    echo "Installing libraries on macOS..."
    brew install git ripgrep xclip jq tldr python
    brew install fzf && "$(brew --prefix)/opt/fzf/install"
else
    echo "Installing libraries on Linux..."
    sudo apt -y update
    sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip
    if [ -z "${FZF_DIR:-}" ]; then
        export FZF_DIR="$HOME/.fzf"
    fi
    if [ ! -d "$FZF_DIR" ]; then
        git clone https://github.com/junegunn/fzf.git "$FZF_DIR"
        "$FZF_DIR/install" --all
    fi
fi
