#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "Installing Node, npm, Deno, and Bun..."

if [[ "$(uname)" == "Darwin" ]]; then
    brew install node
else
    sudo apt update && sudo apt install -y nodejs npm unzip
fi

# Configure npm to use a local prefix
npm config set prefix "$HOME/.local/npm"

# Install and use the 'n' tool to switch to LTS version
npm install -g n
n lts

# Install the neovim npm package globally
npm install -g neovim

# Install Deno
curl -fsSL https://deno.land/install.sh | sh

# Install Bun
curl -fsSL https://bun.sh/install | bash

echo "Node, Deno, and Bun installation completed."

