#!/usr/bin/env bash

if [[ "$(uname)" == "Darwin" ]]; then
    brew install php
    /bin/bash -c "$(curl -fsSL https://php.new/install/mac/8.4)"
else
    /bin/bash -c "$(curl -fsSL https://php.new/install/linux/8.4)"
fi

mv ~/.profile ~/.php_profile

