#!/usr/bin/env bash

if [[ "$i(uname)" == "Darwin" ]]; then
    brew install rust
else
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

cargo install stylua --features luajit
