#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [[ "$(uname)" == "Darwin" ]]; then
    echo "Installing Tmux via Homebrew..."
    brew install tmux
else
    echo "Installing Tmux..."
    sudo apt update && sudo apt install -y tmux
fi

echo "Tmux installation completed."
