#!/usr/bin/env bash

if [[ "$i(uname)" == "Darwin" ]]; then
    brew install zsh
else
    sudo apt update && sudo apt install -y zsh
fi

hash -r
sudo chsh -s $(command -v zsh) "$USER"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


