#!/usr/bin/env bash

if [[ "$i(uname)" == "Darwin" ]]; then
    brew install zsh
else
    sudo apt update && sudo apt install zsh
fi

hash -r
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
