#!/usr/bin/env bash
: "${DEV_ENV:=$HOME/dev}"

# Install Git if missing
if ! command -v git &>/dev/null; then
    if [[ "$(uname)" == "Darwin" ]]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install git
    else
        sudo apt -y update && sudo apt -y install git
    fi
fi

# Ensure ~/personal directory exists
if [ ! -d "$HOME/personal" ]; then
    mkdir -p "$HOME/personal"
fi

# Clone repo if it doesn't already exist
if [ ! -d "$HOME/env" ]; then
    git clone https://github.com/thenameiswiiwin/.dotfiles "$HOME/env"
else
    echo "Repo already exists at $HOME/env. Skipping clone."
fi

# Run the setup script
pushd "$HOME/env" || exit 1
./run
popd
