# Catppuccin Mocha theme for lazygit
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#fab387" # Peach (Catppuccin Mocha)
      - bold
    inactiveBorderColor:
      - "#6c7086" # Overlay0
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#45475a" # Surface1
    cherryPickedCommitFgColor:
      - "#f5e0dc" # Rosewater
    unstagedChangesColor:
      - "#f38ba8" # Red
    defaultFgColor:
      - "#cdd6f4" # Text
    searchingActiveBorderColor:
      - "#f9e2af" # Yellow

  authorColors:
    "*": "#b4befe" # Lavender

