#!/usr/bin/env bash

brew install --cask 1password
brew install --cask arc
brew install --cask figma
brew install --cask nordvpn
brew install --cask spotify

echo -e "\e[1;34m[INFO]\e[0m GUI script completed."
