#!/usr/bin/env bash

brew install git
brew install ripgrep
brew install wget
brew install xclip
brew install jq
brew install tldr
brew install fd
brew install fzf
brew install tree

echo -e "\e[1;34m[INFO]\e[0m Libs script completed."
