#!/usr/bin/env bash

brew install php
brew install composer
composer global require laravel/installer

if [[ -f "$HOME/.profile" ]]; then
    mv ~/.profile ~/.php_profile
fi

echo -e "\e[1;34m[INFO]\e[0m PHP script completed."
