#!/usr/bin/env bash
set +e

brew install rustup || true
rustup default stable || true

export PATH="$HOME/.cargo/bin:$PATH"
cargo install stylua --features luajit || true

echo -e "\e[1;34m[INFO]\e[0m Rust script completed."
